services:

  naming-server:
    image: wwtr35/naming-server:latest
    mem_limit: 700m
    ports:
      - "8761:8761"
    networks:
      - currency-network

  users-service:
    image: wwtr35/users-service:latest
    mem_limit: 700m
    ports:
      - "8770:8770"
    networks:
      - currency-network
    depends_on:
      - naming-server
    environment:
      EUREKA.CLIENT.SERVICE-URL.DEFAULTZONE: http://naming-server:8761/eureka

  bank-account:
    image: wwtr35/bank-account:latest
    mem_limit: 700m
    ports:
      - "8200:8200"
    networks:
      - currency-network
    depends_on:
      - naming-server
    environment:
      EUREKA.CLIENT.SERVICE-URL.DEFAULTZONE: http://naming-server:8761/eureka

  crypto-wallet:
    image: wwtr35/crypto-wallet:latest
    mem_limit: 700m
    ports:
      - "8300:8300"
    networks:
      - currency-network
    depends_on:
      - naming-server
    environment:
      EUREKA.CLIENT.SERVICE-URL.DEFAULTZONE: http://naming-server:8761/eureka

  currency-exchange:
    image: wwtr35/currency-exchange:latest
    mem_limit: 700m
    ports:
      - "8000:8000"
    networks:
      - currency-network
    depends_on:
      - naming-server
    environment:
      EUREKA.CLIENT.SERVICE-URL.DEFAULTZONE: http://naming-server:8761/eureka

  currency-conversion:
    image: wwtr35/currency-conversion:latest
    mem_limit: 700m
    ports:
      - "8100:8100"
    networks:
      - currency-network
    depends_on:
      - naming-server
      - currency-exchange
      - bank-account
    environment:
      EUREKA.CLIENT.SERVICE-URL.DEFAULTZONE: http://naming-server:8761/eureka

  crypto-exchange:
    image: wwtr35/crypto-exchange:latest
    mem_limit: 700m
    ports:
      - "8400:8400"
    networks:
      - currency-network
    depends_on:
      - naming-server
    environment:
      EUREKA.CLIENT.SERVICE-URL.DEFAULTZONE: http://naming-server:8761/eureka

  trade-service:
    image: wwtr35/trade-service:latest
    mem_limit: 700m
    ports:
      - "8600:8600"
    networks:
      - currency-network
    depends_on:
      - naming-server
      - crypto-exchange
      - currency-conversion
      - crypto-wallet
      - bank-account
    environment:
      EUREKA.CLIENT.SERVICE-URL.DEFAULTZONE: http://naming-server:8761/eureka

  api-gateway:
    image: wwtr35/api-gateway:latest
    mem_limit: 700m
    ports:
      - "8765:8765"
    networks:
      - currency-network
    depends_on:
      - naming-server
      - users-service
    environment:
      EUREKA.CLIENT.SERVICE-URL.DEFAULTZONE: http://naming-server:8761/eureka

networks:
  currency-network:
