spring.application.name=trade-service
server.port=8600

eureka.client.service-url.defaultZone=http://localhost:8761/eureka

management.endpoints.web.exposure.include=health,circuitbreakers,circuitbreakerevents
management.endpoint.health.show-details=always

## CircuitBreaker
#Minimalni broj zahteva potreban za racunanje praga uspesnosti
resilience4j.circuitbreaker.instances.cb.minimum-number-of-calls=1
#Ako je 50% zahteva neuspesno (ili sporo) CB prelazi u OPEN stanje
resilience4j.circuitbreaker.instances.cb.failure-rate-threshold=50
#Duzina trajanja OPEN stanja
resilience4j.circuitbreaker.instances.cb.wait-duration-in-open-state=20s
#Broj dozvoljenih zahteva u poluotvorenom stanju
resilience4j.circuitbreaker.instances.cb.permitted-number-of-calls-in-half-open-state=4
#Neograniceno vreme trajanja HALF-OPEN stanja
resilience4j.circuitbreaker.instances.cb.max-wait-duration-in-half-open-state=0
#Konfiguracija zahteva koje ce CB klasifikovati kao "spore(latentne) zahteva"
resilience4j.circuitbreaker.instances.cb.slow-call-duration-threshold=10s
resilience4j.circuitbreaker.instances.cb.slow-call-rate-threshold=50

#Konfiguracija RETRY mehanizma
#Vreme cekanja izmedju ponovnih zahteva
resilience4j.retry.instances.default.wait-duration=20s
#Broj zahteva koje primenjuje retry mehanizam
resilience4j.retry.instances.default.max-attempts=3
